// Teacher Constant's
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_RESPONSE = "AUTH_RESPONSE";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_ERROR_EMPTY = "AUTH_ERROR_EMPTY";
export const CREATE_CODE = "CREATE_CODE";
export const CHECK_CODE = "CHECK_CODE";

// Class Constant's
export const CLASS_REQUEST = "CLASS_REQUEST";
export const CLASS_RESPONSE = "CLASS_RESPONSE";
export const ADD_CLASS_RESPONSE = "ADD_CLASS_RESPONSE";
export const EDIT_CLASS_RESPONSE = "EDIT_CLASS_RESPONSE";
export const REMOVE_CLASS_RESPONSE = "REMOVE_CLASS_RESPONSE";
export const CLASS_ERROR = "CLASS_ERROR";
export const CLASS_ERROR_EMPTY = "CLASS_ERROR_EMPTY";

// Student Constant's
export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_RESPONSE = "STUDENT_RESPONSE";
export const ADD_STUDENT_RESPONSE = "ADD_STUDENT_RESPONSE";
export const EDIT_STUDENT_RESPONSE = "EDIT_STUDENT_RESPONSE";
export const REMOVE_STUDENT_RESPONSE = "REMOVE_STUDENT_RESPONSE";
export const STUDENT_ERROR = "STUDENT_ERROR";
export const STUDENT_ERROR_EMPTY = "STUDENT_ERROR_EMPTY";


// Exam Constant's
export const EXAM_REQUEST = "EXAM_REQUEST";
export const EXAM_RESPONSE = "EXAM_RESPONSE";
export const ADD_EXAM_RESPONSE = "ADD_EXAM_RESPONSE";
export const EDIT_EXAM_RESPONSE = "EDIT_EXAM_RESPONSE";
export const REMOVE_EXAM_RESPONSE = "REMOVE_EXAM_RESPONSE";
export const EXAM_ERROR = "EXAM_ERROR";
export const EXAM_ERROR_EMPTY = "EXAM_ERROR_EMPTY";